-- Drop old data and re-insert with real product data
DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM product_images;
DELETE FROM products;
DELETE FROM collections;
DELETE FROM customers;

-- Collections by fabric
INSERT INTO collections (name, slug, sort_order, is_active, product_count) VALUES
('Diamond Chiffon', 'diamond-chiffon', 1, true, 10),
('Chinoon', 'chinoon', 2, true, 8),
('Crepe', 'crepe', 3, true, 2),
('Silk', 'silk', 4, true, 1);

-- Products
INSERT INTO products (name, brand, price, slug, description, dimensions, care_instructions, customisation_info, fabric, occasion, tag, availability, is_active) VALUES
('Batik Print — Gajree', 'ChhumChhum', 350000, 'batik-gajree', 'This elegant diamond chiffon saree is hand-printed using the timeless art of batik — a traditional technique known for its intricate patterns, rich textures, and artistic uniqueness.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Festive','Party Wear'], 'Best Seller', 'ready', true),
('Batik Print — Sea Green', 'ChhumChhum', 350000, 'batik-seagreen', 'This elegant diamond chiffon saree is hand-printed using the timeless art of batik. Lightweight and graceful, making it truly one of a kind.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Festive','Party Wear'], NULL, 'ready', true),
('Batik Print — Navy', 'ChhumChhum', 350000, 'batik-navy', 'This elegant diamond chiffon saree is hand-printed using the timeless art of batik. Each piece reflects craftsmanship and heritage.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Festive','Party Wear'], NULL, 'ready', true),
('Chinoon Chick Pallu — Navy', 'ChhumChhum', 420000, 'chinoon-chick-navy', 'This exquisite Chinoon saree showcases a rich pure zari border complemented by an elegant self-weaving design. Features a zari-lined pallu with matching buti blouse.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Viscose Chinoon', ARRAY['Wedding','Festive'], NULL, 'ready', true),
('Chinoon Chick Pallu — Rani', 'ChhumChhum', 420000, 'chinoon-chick-rani', 'This exquisite Chinoon saree showcases a rich pure zari border with elegant self-weaving. The subtle shimmer of zari adds timeless elegance.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Viscose Chinoon', ARRAY['Wedding','Festive'], 'New', 'ready', true),
('Chinoon Chick Pallu — Red', 'ChhumChhum', 420000, 'chinoon-chick-red', 'This exquisite Chinoon saree showcases a rich pure zari border with an elegant self-weaving design. Lightweight yet luxurious.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Viscose Chinoon', ARRAY['Wedding','Festive'], NULL, 'ready', true),
('Chinoon Digital Handwork — Bottle Green', 'ChhumChhum', 380000, 'chinoon-digital-bottlegreen', 'This stunning chinoon saree features vibrant digital prints with striking floral patterns. Enhanced with delicate hand embroidery.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Viscose Chinoon', ARRAY['Festive','Party Wear'], NULL, 'ready', true),
('Chinoon Digital Handwork — Gajree', 'ChhumChhum', 380000, 'chinoon-digital-gajree', 'This elegant chinoon saree is adorned with vibrant digital floral prints. Beautifully enhanced with delicate hand embroidery.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Viscose Chinoon', ARRAY['Festive','Party Wear'], NULL, 'ready', true),
('Chinoon Digital Handwork — Black', 'ChhumChhum', 380000, 'chinoon-digital-black', 'This eye-catching chinoon saree makes a bold yet elegant statement with striking digital prints and fine handwork detailing.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Viscose Chinoon', ARRAY['Festive','Party Wear'], NULL, 'ready', true),
('Crepe Digital — Mustard', 'ChhumChhum', 360000, 'crep-digital-mustard', 'This mustard-colored crepe saree, adorned with artistic digital prints and intricate handwork, is a perfect choice for any occasion.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Viscose Crepe', ARRAY['Party Wear','Festive'], NULL, 'ready', true),
('Crepe Digital Handwork — Peach', 'ChhumChhum', 390000, 'crep-digital-handwork', 'This peach-toned saree inspired by Ajrak prints is a graceful blend of tradition and modern design with delicate handwork.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Viscose Crepe', ARRAY['Festive','Party Wear'], NULL, 'ready', true),
('Gadar Contraz — Parrot', 'ChhumChhum', 450000, 'gadar-contraz-parrot', 'This exquisite diamond chiffon saree is meticulously hand-painted by skilled artisans. Complemented by a contrast blouse.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Wedding','Festive'], 'Best Seller', 'made_to_order', true),
('Gadar Contraz — Gold', 'ChhumChhum', 450000, 'gadar-contraz-gold', 'This exquisite diamond chiffon saree is meticulously hand-painted. Complemented by a contrast blouse for striking balance.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Wedding','Festive'], NULL, 'made_to_order', true),
('Gadar Contraz — Pink', 'ChhumChhum', 450000, 'gadar-contraz-pink', 'This exquisite diamond chiffon saree is meticulously hand-painted. Each piece is truly unique. Complemented by a contrast blouse.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Wedding','Party Wear'], NULL, 'made_to_order', true),
('Gadar Hand-painted — Gold', 'ChhumChhum', 430000, 'gadar-gold2', 'This exquisite diamond chiffon saree is meticulously hand-painted. Complemented by a chinoon blouse for refined charm.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Festive','Party Wear'], 'New', 'made_to_order', true),
('Gadar Hand-painted — Pink', 'ChhumChhum', 430000, 'gadar-pink2', 'This exquisite diamond chiffon saree is meticulously hand-painted. Complemented by a chinoon blouse for sophistication.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Festive','Party Wear'], NULL, 'made_to_order', true),
('Chinoon Jacquard Heavy Blouse', 'ChhumChhum', 480000, 'chinoon-jaq-heavy-blouse', 'This elegant chinoon saree features a smooth plain drape enhanced with a heavy zari weaving blouse with intricate figure motifs.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Viscose Chinoon', ARRAY['Wedding','Festive'], NULL, 'ready', true),
('HO Silk Chick Pallu Cutdana', 'ChhumChhum', 520000, 'ho-chick-cutdana', 'This stunning HO silk saree blends richness with refined simplicity. Enhanced with a zari-lined pallu and heavy woven zari blouse.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'HO Silk', ARRAY['Wedding','Festive'], NULL, 'ready', true),
('JP Gota Patti — Peacock', 'ChhumChhum', 490000, 'jp-gota1-peacock', 'This diamond chiffon saree showcases exquisite gotta patti work, a traditional Rajasthani appliqué technique from the Mughal era.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Wedding','Festive'], NULL, 'made_to_order', true),
('JP Gota Patti — Red', 'ChhumChhum', 490000, 'jp-gota1-red', 'This diamond chiffon saree showcases exquisite gotta patti work. Known for its intricate detailing and royal heritage.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Wedding','Festive'], NULL, 'made_to_order', true),
('JP Gota Patti 2', 'ChhumChhum', 490000, 'jp-gota2', 'This diamond chiffon saree showcases exquisite gotta patti work with a perfect balance of grace and grandeur.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Wedding','Festive'], NULL, 'made_to_order', true),
('JP Gota Patti 5 — Mustard', 'ChhumChhum', 490000, 'jp-gota5-mustard', 'This diamond chiffon saree showcases exquisite gotta patti work dating back to the Mughal era.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Wedding','Festive'], NULL, 'made_to_order', true),
('JP Gota Patti 5 — Coffee Brown', 'ChhumChhum', 490000, 'jp-gota5-coffee', 'This diamond chiffon saree showcases exquisite gotta patti work. Heritage craftsmanship with contemporary sophistication.', 'Saree: 5.50 mtr | Blouse: 1 mtr unstitched', 'Dry clean only', 'WhatsApp: +91 99034 84121', 'Diamond Chiffon', ARRAY['Wedding','Festive'], NULL, 'made_to_order', true);
